//
//Copyright 2026 The Swarmada Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/fleet_adapter/v1/fleet_adapter.proto

package fleetadapterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetAdapterService_ControlStream_FullMethodName = "/fleet_adapter.v1.FleetAdapterService/ControlStream"
	FleetAdapterService_SafetyStream_FullMethodName  = "/fleet_adapter.v1.FleetAdapterService/SafetyStream"
)

// FleetAdapterServiceClient is the client API for FleetAdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetAdapterServiceClient interface {
	// ControlStream is the primary persistent connection. The adapter opens it
	// and sends AdapterHello first; the control plane replies with HelloAck.
	// Thereafter both sides multiplex:
	//
	//	adapter → control plane : AdapterMessage  (register/discover, telemetry,
	//	                          action status, command results, heartbeat replies)
	//	control plane → adapter : ControlPlaneMessage (acks, pushed Commands,
	//	                          heartbeat requests)
	//
	// NOTE: Estop/EstopAck travel on SafetyStream, NOT on ControlStream.
	// Command.estop (field 5) and CommandResult.estop (field 6) are retained for
	// wire-format compatibility but are DEPRECATED — see annotations below.
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdapterMessage, ControlPlaneMessage], error)
	// SafetyStream is the ONLY additional RPC in this service. It exists because
	// ControlStream multiplexes bulk telemetry, large CapabilitiesSnapshots, and
	// frequent ActionStatusUpdates alongside Commands. Under load an Estop Command
	// can queue behind this traffic or stall on the HTTP/2 flow-control window,
	// violating the <500 ms estop SLA (RFC-0001 #safety-timing-requirements, RA-6).
	//
	// Rejected alternative — HTTP/2 stream priority (RFC 7540 §5.3) within a
	// single ControlStream: gRPC libraries (grpc-go, grpc-java, grpc-core) do not
	// expose per-message priority to the application layer, and a flow-control
	// window that is full stalls ALL frames on the stream regardless of priority.
	// Physical channel isolation via a dedicated stream is the only mechanism
	// that guarantees estop is never queued behind bulk data.
	//
	// Invariants:
	//   - Same mTLS identity and per-robot authorization as ControlStream.
	//   - Carries ONLY Estop Commands and EstopAck results (plus optional
	//     safety-critical PauseCapabilities / PauseResult).
	//   - Permanently empty in steady state — no telemetry, no action commands.
	//   - EstopLatencyViolation events (RFC-0001 #safety-timing-requirements) are measured on this stream.
	//   - Adapter MUST open SafetyStream in the same dial step as ControlStream.
	//     If SafetyStream cannot be established the adapter MUST NOT declare
	//     itself healthy and MUST retry.
	//   - Estop and EstopAck messages are REUSED — not duplicated — via the
	//     AdapterSafetyMessage / ControlPlaneSafetyMessage envelopes below.
	SafetyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdapterSafetyMessage, ControlPlaneSafetyMessage], error)
}

type fleetAdapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetAdapterServiceClient(cc grpc.ClientConnInterface) FleetAdapterServiceClient {
	return &fleetAdapterServiceClient{cc}
}

func (c *fleetAdapterServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdapterMessage, ControlPlaneMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetAdapterService_ServiceDesc.Streams[0], FleetAdapterService_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdapterMessage, ControlPlaneMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetAdapterService_ControlStreamClient = grpc.BidiStreamingClient[AdapterMessage, ControlPlaneMessage]

func (c *fleetAdapterServiceClient) SafetyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdapterSafetyMessage, ControlPlaneSafetyMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetAdapterService_ServiceDesc.Streams[1], FleetAdapterService_SafetyStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdapterSafetyMessage, ControlPlaneSafetyMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetAdapterService_SafetyStreamClient = grpc.BidiStreamingClient[AdapterSafetyMessage, ControlPlaneSafetyMessage]

// FleetAdapterServiceServer is the server API for FleetAdapterService service.
// All implementations must embed UnimplementedFleetAdapterServiceServer
// for forward compatibility.
type FleetAdapterServiceServer interface {
	// ControlStream is the primary persistent connection. The adapter opens it
	// and sends AdapterHello first; the control plane replies with HelloAck.
	// Thereafter both sides multiplex:
	//
	//	adapter → control plane : AdapterMessage  (register/discover, telemetry,
	//	                          action status, command results, heartbeat replies)
	//	control plane → adapter : ControlPlaneMessage (acks, pushed Commands,
	//	                          heartbeat requests)
	//
	// NOTE: Estop/EstopAck travel on SafetyStream, NOT on ControlStream.
	// Command.estop (field 5) and CommandResult.estop (field 6) are retained for
	// wire-format compatibility but are DEPRECATED — see annotations below.
	ControlStream(grpc.BidiStreamingServer[AdapterMessage, ControlPlaneMessage]) error
	// SafetyStream is the ONLY additional RPC in this service. It exists because
	// ControlStream multiplexes bulk telemetry, large CapabilitiesSnapshots, and
	// frequent ActionStatusUpdates alongside Commands. Under load an Estop Command
	// can queue behind this traffic or stall on the HTTP/2 flow-control window,
	// violating the <500 ms estop SLA (RFC-0001 #safety-timing-requirements, RA-6).
	//
	// Rejected alternative — HTTP/2 stream priority (RFC 7540 §5.3) within a
	// single ControlStream: gRPC libraries (grpc-go, grpc-java, grpc-core) do not
	// expose per-message priority to the application layer, and a flow-control
	// window that is full stalls ALL frames on the stream regardless of priority.
	// Physical channel isolation via a dedicated stream is the only mechanism
	// that guarantees estop is never queued behind bulk data.
	//
	// Invariants:
	//   - Same mTLS identity and per-robot authorization as ControlStream.
	//   - Carries ONLY Estop Commands and EstopAck results (plus optional
	//     safety-critical PauseCapabilities / PauseResult).
	//   - Permanently empty in steady state — no telemetry, no action commands.
	//   - EstopLatencyViolation events (RFC-0001 #safety-timing-requirements) are measured on this stream.
	//   - Adapter MUST open SafetyStream in the same dial step as ControlStream.
	//     If SafetyStream cannot be established the adapter MUST NOT declare
	//     itself healthy and MUST retry.
	//   - Estop and EstopAck messages are REUSED — not duplicated — via the
	//     AdapterSafetyMessage / ControlPlaneSafetyMessage envelopes below.
	SafetyStream(grpc.BidiStreamingServer[AdapterSafetyMessage, ControlPlaneSafetyMessage]) error
	mustEmbedUnimplementedFleetAdapterServiceServer()
}

// UnimplementedFleetAdapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetAdapterServiceServer struct{}

func (UnimplementedFleetAdapterServiceServer) ControlStream(grpc.BidiStreamingServer[AdapterMessage, ControlPlaneMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedFleetAdapterServiceServer) SafetyStream(grpc.BidiStreamingServer[AdapterSafetyMessage, ControlPlaneSafetyMessage]) error {
	return status.Errorf(codes.Unimplemented, "method SafetyStream not implemented")
}
func (UnimplementedFleetAdapterServiceServer) mustEmbedUnimplementedFleetAdapterServiceServer() {}
func (UnimplementedFleetAdapterServiceServer) testEmbeddedByValue()                             {}

// UnsafeFleetAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetAdapterServiceServer will
// result in compilation errors.
type UnsafeFleetAdapterServiceServer interface {
	mustEmbedUnimplementedFleetAdapterServiceServer()
}

func RegisterFleetAdapterServiceServer(s grpc.ServiceRegistrar, srv FleetAdapterServiceServer) {
	// If the following call pancis, it indicates UnimplementedFleetAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetAdapterService_ServiceDesc, srv)
}

func _FleetAdapterService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetAdapterServiceServer).ControlStream(&grpc.GenericServerStream[AdapterMessage, ControlPlaneMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetAdapterService_ControlStreamServer = grpc.BidiStreamingServer[AdapterMessage, ControlPlaneMessage]

func _FleetAdapterService_SafetyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetAdapterServiceServer).SafetyStream(&grpc.GenericServerStream[AdapterSafetyMessage, ControlPlaneSafetyMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetAdapterService_SafetyStreamServer = grpc.BidiStreamingServer[AdapterSafetyMessage, ControlPlaneSafetyMessage]

// FleetAdapterService_ServiceDesc is the grpc.ServiceDesc for FleetAdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetAdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet_adapter.v1.FleetAdapterService",
	HandlerType: (*FleetAdapterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlStream",
			Handler:       _FleetAdapterService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SafetyStream",
			Handler:       _FleetAdapterService_SafetyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/fleet_adapter/v1/fleet_adapter.proto",
}

const (
	EdgeService_EdgeStream_FullMethodName = "/fleet_adapter.v1.EdgeService/EdgeStream"
)

// EdgeServiceClient is the client API for EdgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// EdgeService — served by the Zone Controller EDGE NODE on the facility LAN,
// not by the control plane (RA-10-D1, RFC-0001 #fleet-adapter-protocol-the-edge-stream, RFC-0001 #safety-edge-headless-emergency-stop). The adapter dials
// every endpoint listed in RegisterAck.edge_endpoints and holds one EdgeStream
// per edge node, with the same dial-out, mTLS, and reconnect-backoff
// discipline as the ControlStream. The stream survives control-plane
// partitions: it is the data source for headless boundary-breach detection
// and the delivery path for headless estop.
type EdgeServiceClient interface {
	EdgeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdapterEdgeMessage, EdgeControlMessage], error)
}

type edgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeServiceClient(cc grpc.ClientConnInterface) EdgeServiceClient {
	return &edgeServiceClient{cc}
}

func (c *edgeServiceClient) EdgeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdapterEdgeMessage, EdgeControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdgeService_ServiceDesc.Streams[0], EdgeService_EdgeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdapterEdgeMessage, EdgeControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeService_EdgeStreamClient = grpc.BidiStreamingClient[AdapterEdgeMessage, EdgeControlMessage]

// EdgeServiceServer is the server API for EdgeService service.
// All implementations must embed UnimplementedEdgeServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// EdgeService — served by the Zone Controller EDGE NODE on the facility LAN,
// not by the control plane (RA-10-D1, RFC-0001 #fleet-adapter-protocol-the-edge-stream, RFC-0001 #safety-edge-headless-emergency-stop). The adapter dials
// every endpoint listed in RegisterAck.edge_endpoints and holds one EdgeStream
// per edge node, with the same dial-out, mTLS, and reconnect-backoff
// discipline as the ControlStream. The stream survives control-plane
// partitions: it is the data source for headless boundary-breach detection
// and the delivery path for headless estop.
type EdgeServiceServer interface {
	EdgeStream(grpc.BidiStreamingServer[AdapterEdgeMessage, EdgeControlMessage]) error
	mustEmbedUnimplementedEdgeServiceServer()
}

// UnimplementedEdgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeServiceServer struct{}

func (UnimplementedEdgeServiceServer) EdgeStream(grpc.BidiStreamingServer[AdapterEdgeMessage, EdgeControlMessage]) error {
	return status.Errorf(codes.Unimplemented, "method EdgeStream not implemented")
}
func (UnimplementedEdgeServiceServer) mustEmbedUnimplementedEdgeServiceServer() {}
func (UnimplementedEdgeServiceServer) testEmbeddedByValue()                     {}

// UnsafeEdgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeServiceServer will
// result in compilation errors.
type UnsafeEdgeServiceServer interface {
	mustEmbedUnimplementedEdgeServiceServer()
}

func RegisterEdgeServiceServer(s grpc.ServiceRegistrar, srv EdgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedEdgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeService_ServiceDesc, srv)
}

func _EdgeService_EdgeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EdgeServiceServer).EdgeStream(&grpc.GenericServerStream[AdapterEdgeMessage, EdgeControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeService_EdgeStreamServer = grpc.BidiStreamingServer[AdapterEdgeMessage, EdgeControlMessage]

// EdgeService_ServiceDesc is the grpc.ServiceDesc for EdgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet_adapter.v1.EdgeService",
	HandlerType: (*EdgeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EdgeStream",
			Handler:       _EdgeService_EdgeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/fleet_adapter/v1/fleet_adapter.proto",
}
