# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fleet_adapter.v1 import fleet_adapter_pb2 as fleet__adapter_dot_v1_dot_fleet__adapter__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fleet_adapter/v1/fleet_adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetAdapterServiceStub:
    """═══════════════════════════════════════════════════════════════════════════
    FleetAdapterService — adapter-initiated bidirectional stream topology

    TOPOLOGY (RFC-0001 #fleet-adapter-protocol-the-controlstream-service; supersedes the Stage-2 interim direction).

    The control plane is the gRPC SERVER. Each Fleet Adapter is the CLIENT: it
    dials the control plane and opens two long-lived bidirectional streams:
    ControlStream  — all operational traffic (actions, telemetry, heartbeat)
    SafetyStream   — emergency-stop only (RFC-0001 #fleet-adapter-protocol-why-grpc-and-why-adapter-initiated-bidirectional-streams RA-6; see SafetyStream RPC)
    This topology is simultaneously:
    * NAT/firewall friendly — robots and adapters never need a routable address
    or an inbound listener (a hard requirement on warehouse/hospital Wi-Fi); and
    * able to PUSH control-plane → adapter commands (action assignment, and above
    all emergency stop) to a client that dialed in.

    The earlier flat unary design (control plane as server with AssignAction/Estop
    as ordinary RPCs) cannot do the second: a server cannot initiate a unary call
    to a client. That inversion made every control-plane → adapter operation —
    estop included — non-functional (architectural review R2). ControlStream
    resolves it: commands travel DOWN the stream, results travel UP, correlated by
    Command.command_id.

    One ControlStream multiplexes every robot an adapter manages; each message
    carries robot_id. All connections use mTLS (RFC-0001 #security-transport-security); the adapter's client
    certificate IS its identity, and per-robot authorization is enforced
    server-side by checking each message's robot_id against that identity
    (FleetAdapter.spec.servesRobotClasses + namespace) — there is no per-robot JWT.

    SAFETY HARDENING (carried over from the Stage-2 proto pass):
    * fencing tokens on AssignAction/CancelAction (anti double-execution, R2/RA-2);
    * adapter-CONFIRMED estop via EstopAck.state (never telemetry-inferred, R4);
    * proto3 explicit-presence (`optional`) on safety-relevant scalars (RA-3b).
    ═══════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStream = channel.stream_stream(
                '/fleet_adapter.v1.FleetAdapterService/ControlStream',
                request_serializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterMessage.SerializeToString,
                response_deserializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.ControlPlaneMessage.FromString,
                _registered_method=True)
        self.SafetyStream = channel.stream_stream(
                '/fleet_adapter.v1.FleetAdapterService/SafetyStream',
                request_serializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterSafetyMessage.SerializeToString,
                response_deserializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.ControlPlaneSafetyMessage.FromString,
                _registered_method=True)


class FleetAdapterServiceServicer:
    """═══════════════════════════════════════════════════════════════════════════
    FleetAdapterService — adapter-initiated bidirectional stream topology

    TOPOLOGY (RFC-0001 #fleet-adapter-protocol-the-controlstream-service; supersedes the Stage-2 interim direction).

    The control plane is the gRPC SERVER. Each Fleet Adapter is the CLIENT: it
    dials the control plane and opens two long-lived bidirectional streams:
    ControlStream  — all operational traffic (actions, telemetry, heartbeat)
    SafetyStream   — emergency-stop only (RFC-0001 #fleet-adapter-protocol-why-grpc-and-why-adapter-initiated-bidirectional-streams RA-6; see SafetyStream RPC)
    This topology is simultaneously:
    * NAT/firewall friendly — robots and adapters never need a routable address
    or an inbound listener (a hard requirement on warehouse/hospital Wi-Fi); and
    * able to PUSH control-plane → adapter commands (action assignment, and above
    all emergency stop) to a client that dialed in.

    The earlier flat unary design (control plane as server with AssignAction/Estop
    as ordinary RPCs) cannot do the second: a server cannot initiate a unary call
    to a client. That inversion made every control-plane → adapter operation —
    estop included — non-functional (architectural review R2). ControlStream
    resolves it: commands travel DOWN the stream, results travel UP, correlated by
    Command.command_id.

    One ControlStream multiplexes every robot an adapter manages; each message
    carries robot_id. All connections use mTLS (RFC-0001 #security-transport-security); the adapter's client
    certificate IS its identity, and per-robot authorization is enforced
    server-side by checking each message's robot_id against that identity
    (FleetAdapter.spec.servesRobotClasses + namespace) — there is no per-robot JWT.

    SAFETY HARDENING (carried over from the Stage-2 proto pass):
    * fencing tokens on AssignAction/CancelAction (anti double-execution, R2/RA-2);
    * adapter-CONFIRMED estop via EstopAck.state (never telemetry-inferred, R4);
    * proto3 explicit-presence (`optional`) on safety-relevant scalars (RA-3b).
    ═══════════════════════════════════════════════════════════════════════════

    """

    def ControlStream(self, request_iterator, context):
        """ControlStream is the primary persistent connection. The adapter opens it
        and sends AdapterHello first; the control plane replies with HelloAck.
        Thereafter both sides multiplex:
        adapter → control plane : AdapterMessage  (register/discover, telemetry,
        action status, command results, heartbeat replies)
        control plane → adapter : ControlPlaneMessage (acks, pushed Commands,
        heartbeat requests)
        NOTE: Estop/EstopAck travel on SafetyStream, NOT on ControlStream.
        Command.estop (field 5) and CommandResult.estop (field 6) are retained for
        wire-format compatibility but are DEPRECATED — see annotations below.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SafetyStream(self, request_iterator, context):
        """SafetyStream is the ONLY additional RPC in this service. It exists because
        ControlStream multiplexes bulk telemetry, large CapabilitiesSnapshots, and
        frequent ActionStatusUpdates alongside Commands. Under load an Estop Command
        can queue behind this traffic or stall on the HTTP/2 flow-control window,
        violating the <500 ms estop SLA (RFC-0001 #safety-timing-requirements, RA-6).

        Rejected alternative — HTTP/2 stream priority (RFC 7540 §5.3) within a
        single ControlStream: gRPC libraries (grpc-go, grpc-java, grpc-core) do not
        expose per-message priority to the application layer, and a flow-control
        window that is full stalls ALL frames on the stream regardless of priority.
        Physical channel isolation via a dedicated stream is the only mechanism
        that guarantees estop is never queued behind bulk data.

        Invariants:
        * Same mTLS identity and per-robot authorization as ControlStream.
        * Carries ONLY Estop Commands and EstopAck results (plus optional
        safety-critical PauseCapabilities / PauseResult).
        * Permanently empty in steady state — no telemetry, no action commands.
        * EstopLatencyViolation events (RFC-0001 #safety-timing-requirements) are measured on this stream.
        * Adapter MUST open SafetyStream in the same dial step as ControlStream.
        If SafetyStream cannot be established the adapter MUST NOT declare
        itself healthy and MUST retry.
        * Estop and EstopAck messages are REUSED — not duplicated — via the
        AdapterSafetyMessage / ControlPlaneSafetyMessage envelopes below.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetAdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlStream,
                    request_deserializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterMessage.FromString,
                    response_serializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.ControlPlaneMessage.SerializeToString,
            ),
            'SafetyStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SafetyStream,
                    request_deserializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterSafetyMessage.FromString,
                    response_serializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.ControlPlaneSafetyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet_adapter.v1.FleetAdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet_adapter.v1.FleetAdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetAdapterService:
    """═══════════════════════════════════════════════════════════════════════════
    FleetAdapterService — adapter-initiated bidirectional stream topology

    TOPOLOGY (RFC-0001 #fleet-adapter-protocol-the-controlstream-service; supersedes the Stage-2 interim direction).

    The control plane is the gRPC SERVER. Each Fleet Adapter is the CLIENT: it
    dials the control plane and opens two long-lived bidirectional streams:
    ControlStream  — all operational traffic (actions, telemetry, heartbeat)
    SafetyStream   — emergency-stop only (RFC-0001 #fleet-adapter-protocol-why-grpc-and-why-adapter-initiated-bidirectional-streams RA-6; see SafetyStream RPC)
    This topology is simultaneously:
    * NAT/firewall friendly — robots and adapters never need a routable address
    or an inbound listener (a hard requirement on warehouse/hospital Wi-Fi); and
    * able to PUSH control-plane → adapter commands (action assignment, and above
    all emergency stop) to a client that dialed in.

    The earlier flat unary design (control plane as server with AssignAction/Estop
    as ordinary RPCs) cannot do the second: a server cannot initiate a unary call
    to a client. That inversion made every control-plane → adapter operation —
    estop included — non-functional (architectural review R2). ControlStream
    resolves it: commands travel DOWN the stream, results travel UP, correlated by
    Command.command_id.

    One ControlStream multiplexes every robot an adapter manages; each message
    carries robot_id. All connections use mTLS (RFC-0001 #security-transport-security); the adapter's client
    certificate IS its identity, and per-robot authorization is enforced
    server-side by checking each message's robot_id against that identity
    (FleetAdapter.spec.servesRobotClasses + namespace) — there is no per-robot JWT.

    SAFETY HARDENING (carried over from the Stage-2 proto pass):
    * fencing tokens on AssignAction/CancelAction (anti double-execution, R2/RA-2);
    * adapter-CONFIRMED estop via EstopAck.state (never telemetry-inferred, R4);
    * proto3 explicit-presence (`optional`) on safety-relevant scalars (RA-3b).
    ═══════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def ControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fleet_adapter.v1.FleetAdapterService/ControlStream',
            fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterMessage.SerializeToString,
            fleet__adapter_dot_v1_dot_fleet__adapter__pb2.ControlPlaneMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SafetyStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fleet_adapter.v1.FleetAdapterService/SafetyStream',
            fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterSafetyMessage.SerializeToString,
            fleet__adapter_dot_v1_dot_fleet__adapter__pb2.ControlPlaneSafetyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EdgeServiceStub:
    """---------------------------------------------------------------------------
    EdgeService — served by the Zone Controller EDGE NODE on the facility LAN,
    not by the control plane (RA-10-D1, RFC-0001 #fleet-adapter-protocol-the-edge-stream, RFC-0001 #safety-edge-headless-emergency-stop). The adapter dials
    every endpoint listed in RegisterAck.edge_endpoints and holds one EdgeStream
    per edge node, with the same dial-out, mTLS, and reconnect-backoff
    discipline as the ControlStream. The stream survives control-plane
    partitions: it is the data source for headless boundary-breach detection
    and the delivery path for headless estop.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EdgeStream = channel.stream_stream(
                '/fleet_adapter.v1.EdgeService/EdgeStream',
                request_serializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterEdgeMessage.SerializeToString,
                response_deserializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.EdgeControlMessage.FromString,
                _registered_method=True)


class EdgeServiceServicer:
    """---------------------------------------------------------------------------
    EdgeService — served by the Zone Controller EDGE NODE on the facility LAN,
    not by the control plane (RA-10-D1, RFC-0001 #fleet-adapter-protocol-the-edge-stream, RFC-0001 #safety-edge-headless-emergency-stop). The adapter dials
    every endpoint listed in RegisterAck.edge_endpoints and holds one EdgeStream
    per edge node, with the same dial-out, mTLS, and reconnect-backoff
    discipline as the ControlStream. The stream survives control-plane
    partitions: it is the data source for headless boundary-breach detection
    and the delivery path for headless estop.
    """

    def EdgeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EdgeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EdgeStream,
                    request_deserializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterEdgeMessage.FromString,
                    response_serializer=fleet__adapter_dot_v1_dot_fleet__adapter__pb2.EdgeControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet_adapter.v1.EdgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet_adapter.v1.EdgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeService:
    """---------------------------------------------------------------------------
    EdgeService — served by the Zone Controller EDGE NODE on the facility LAN,
    not by the control plane (RA-10-D1, RFC-0001 #fleet-adapter-protocol-the-edge-stream, RFC-0001 #safety-edge-headless-emergency-stop). The adapter dials
    every endpoint listed in RegisterAck.edge_endpoints and holds one EdgeStream
    per edge node, with the same dial-out, mTLS, and reconnect-backoff
    discipline as the ControlStream. The stream survives control-plane
    partitions: it is the data source for headless boundary-breach detection
    and the delivery path for headless estop.
    """

    @staticmethod
    def EdgeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fleet_adapter.v1.EdgeService/EdgeStream',
            fleet__adapter_dot_v1_dot_fleet__adapter__pb2.AdapterEdgeMessage.SerializeToString,
            fleet__adapter_dot_v1_dot_fleet__adapter__pb2.EdgeControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
