#!/usr/bin/env python3
# Copyright 2026 The Swarmada Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ─────────────────────────────────────────────────────────────────────────────
# Regenerates deploy/swarmada/templates/webhook.yaml from config/webhook/manifests.yaml
# (the controller-gen output). Wired as `make helm-sync-webhooks`; the drift guard is
# `make helm-verify-sync`.
#
# WHY THIS EXISTS. The chart's webhook template was hand-maintained, with only a comment
# ("Mirrors config/webhook/manifests.yaml") holding the two in sync and no gate behind it.
# It drifted: the chart declared 4 of 9 webhooks, so a Helm-installed cluster silently did
# not enforce five validators — including the FleetAction cancel-verb SAR and the rollout
# delete guards. That is the failure mode an ungated hand-mirror produces, and it is why
# the CRDs already had hack/sync-helm-crds.sh. This is the webhook twin of it.
#
# FAILURE POLICY. The chart exposes .Values.webhooks.failurePolicy so an operator can
# loosen admission during a break-glass. That knob is applied ONLY to webhooks whose
# generated policy is Fail. A webhook generated as Ignore is emitted as a literal Ignore:
# those are the ADR-0046 estop-actor stampers, where Ignore is the safety property (an
# estop must never be blocked by attribution plumbing) rather than a tuning default, and
# letting the chart value tighten them to Fail would invert that.
# ─────────────────────────────────────────────────────────────────────────────
import os
import sys

import yaml

SRC = "config/webhook/manifests.yaml"
OUT = os.environ.get("OUT", "deploy/swarmada/templates/webhook.yaml")

HEADER = """# GENERATED by hack/sync-helm-webhooks.py from config/webhook/manifests.yaml — DO NOT EDIT.
# Re-run `make helm-sync` after `make manifests` whenever a +kubebuilder:webhook marker changes.
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The Swarmada Authors <maintainers@swarmada.io>

{{- if .Values.webhooks.enabled -}}
{{- $svc := printf "%s-webhook-service" (include "swarmada.fullname" .) -}}
{{- $certName := printf "%s-serving-cert" (include "swarmada.fullname" .) -}}
# ─────────────────────────────────────────────────────────────────────────────
# Admission webhook Service + configurations.
#
# CA bundle:
#   - cert-manager enabled  → the ca-injector fills clientConfig.caBundle via the
#     cert-manager.io/inject-ca-from annotation (see templates/certificate.yaml).
#   - cert-manager disabled → webhooks.caBundle is written into each clientConfig,
#     and you must create the Secret {{ include "swarmada.webhookCertSecret" . }}.
#
# failurePolicy: webhooks generated as Fail render {{ .Values.webhooks.failurePolicy }}
# so an operator can loosen them; webhooks generated as Ignore render a literal Ignore
# (ADR-0046 — attribution must never block a safe stop).
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swarmada.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "swarmada.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook-server
      protocol: TCP
"""

CONFIG_HEAD = """---
apiVersion: admissionregistration.k8s.io/v1
kind: {kind}
metadata:
  name: {{{{ include "swarmada.fullname" . }}}}-{slug}
  labels:
    {{{{- include "swarmada.labels" . | nindent 4 }}}}
  {{{{- if .Values.webhooks.certManager.enabled }}}}
  annotations:
    cert-manager.io/inject-ca-from: {{{{ .Release.Namespace }}}}/{{{{ $certName }}}}
  {{{{- end }}}}
webhooks:
"""


def render_webhook(w):
    """One webhook entry, with the chart's service/caBundle indirection restored."""
    policy = w.get("failurePolicy", "Fail")
    if policy == "Fail":
        policy_line = "{{ .Values.webhooks.failurePolicy }}"
    else:
        policy_line = policy
    out = [
        "  - admissionReviewVersions:",
        "      - v1",
        "    clientConfig:",
        "      service:",
        "        name: {{ $svc }}",
        "        namespace: {{ .Release.Namespace }}",
        f"        path: {w['clientConfig']['service']['path']}",
        "      {{- if and (not .Values.webhooks.certManager.enabled) .Values.webhooks.caBundle }}",
        "      caBundle: {{ .Values.webhooks.caBundle }}",
        "      {{- end }}",
        f"    failurePolicy: {policy_line}",
        f"    name: {w['name']}",
        "    rules:",
    ]
    for r in w.get("rules", []):
        groups = ", ".join(f'"{g}"' for g in r.get("apiGroups", []))
        versions = ", ".join(f'"{v}"' for v in r.get("apiVersions", []))
        ops = ", ".join(f'"{o}"' for o in r.get("operations", []))
        resources = ", ".join(f'"{x}"' for x in r.get("resources", []))
        out += [
            f"      - apiGroups: [{groups}]",
            f"        apiVersions: [{versions}]",
            f"        operations: [{ops}]",
            f"        resources: [{resources}]",
        ]
    out.append(f"    sideEffects: {w.get('sideEffects', 'None')}")
    return "\n".join(out) + "\n"


def main():
    if not os.path.exists(SRC):
        print(f"{SRC} not found; run `make manifests` first", file=sys.stderr)
        return 1
    docs = [d for d in yaml.safe_load_all(open(SRC)) if d]
    by_kind = {d["kind"]: d for d in docs}

    parts = [HEADER]
    total = 0
    for kind, slug in (
        ("MutatingWebhookConfiguration", "mutating-webhook-configuration"),
        ("ValidatingWebhookConfiguration", "validating-webhook-configuration"),
    ):
        cfg = by_kind.get(kind)
        if not cfg or not cfg.get("webhooks"):
            continue
        parts.append(CONFIG_HEAD.format(kind=kind, slug=slug))
        # Sorted by name so the generated file is stable across controller-gen runs.
        for w in sorted(cfg["webhooks"], key=lambda x: x["name"]):
            parts.append(render_webhook(w))
            total += 1
    parts.append("{{- end }}\n")

    with open(OUT, "w") as f:
        f.write("".join(parts))
    print(f"wrote {OUT} ({total} webhooks from {SRC})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
