#!/usr/bin/env bash
# Copyright 2026 The Swarmada Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ─────────────────────────────────────────────────────────────────────────────
# Regenerates deploy/swarmada/templates/crds.yaml from config/crd/bases (the
# controller-gen output). The Helm chart NEVER hand-maintains a second CRD copy:
# this is the single derivation from config/. Run it after `make manifests`
# (wired as `make helm-sync`).
#
# The CRDs ship in templates/ (not Helm's crds/ dir) so `helm upgrade` updates
# their schemas as the alpha API evolves — the crds/ dir installs once and never
# upgrades. Each CRD gets `helm.sh/resource-policy: keep` so `helm uninstall`
# leaves the CRDs in place and never deletes your CustomResources; the whole set
# is gated by .Values.installCRDs for admins who manage CRDs out of band.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="config/crd/bases"
# OUT is overridable so `make helm-verify-sync` can render to a temp file and diff
# against the committed chart CRDs (drift guard).
OUT="${OUT:-deploy/swarmada/templates/crds.yaml}"

{
  cat <<'HDR'
# GENERATED by hack/sync-helm-crds.sh from config/crd/bases — DO NOT EDIT.
# Re-run `make helm-sync` after `make manifests` whenever api/v1 changes.
#
# UPGRADE CAVEAT: CRDs live in templates/ (not the Helm crds/ dir) so that
# `helm upgrade` DOES update their schemas — the crds/ dir would install them
# once and never touch them again. `helm.sh/resource-policy: keep` keeps the
# CRDs (and therefore every CustomResource) on `helm uninstall`; deleting the
# CRDs is a deliberate, manual `kubectl delete crd ...` step. Set
# `installCRDs: false` when a cluster admin applies config/crd out of band.
{{- if .Values.installCRDs }}
HDR

  for f in "$SRC"/swarmada.io_*.yaml; do
    # Inject the keep policy into each CRD's (single) metadata.annotations block,
    # preserving the controller-gen output byte-for-byte otherwise.
    awk '
      /^  annotations:$/ && !injected { print; print "    helm.sh/resource-policy: keep"; injected=1; next }
      { print }
    ' "$f"
  done

  echo '{{- end }}'
} > "$OUT"

n=$(grep -c '^  name: .*\.swarmada\.io$' "$OUT" || true)
echo "wrote $OUT ($n CRDs from $SRC)"
